#!/bin/bash
# Search for and download a specific format with youtube-dl

# This script displays a YouTube video's available formats and asks the user to choose a format to download.
# The user's most recent item on the xclip clipboard is used as input for the video download commands.

# xclip dumps out the clipboard selection
URL=`xclip -o -selection clipboard`

echo "Checking available formats..."

# -F option displays video's available formats without downloading
youtube-dl -F -i $URL

if [ "$?" = "1" ]; then

	exit

else

	echo
	echo "Please enter the desired format code."
	read FORMAT
	# -f option downloads the specified format
	youtube-dl -f $FORMAT $URL

	if [ "$?" = "1" ]; then

		exit

	else

	echo
	echo "Initiating download using the following command:"
	echo youtube-dl -f $FORMAT $URL
	echo "Done."

	fi

fi
